### ISSUE TITLE
Don't create `IInterface` classes

### ISSUE THREAD

**Issue by domesticmouse** [whosramos/FlutterCode-Organization#3]
In the Dart Language Tour there is a section on [Implicit Interfaces](https://dart.dev/guides/language/language-tour#implicit-interfaces) that talks about how every class in Dart has an implicit interface. This is why Dart and Flutter do not have `IUnknown` and friends. Please delete [`IUrlOpen`](https://github.com/whosramoss/clean-dart-github/blob/master/github_commons/lib/shared/utils/url_open/i_url_open.dart) as it is strongly non-idiomatic.

**Comment by whosramoss** [comment]
Issue fixed in [remove IUrlOpen](https://github.com/whosramoss/clean-dart-github/commit/f87029d3444ead2f80d9c58a4b705d9ea1bf9a77), Thanks for the reporting,
